title: Yu-Huan Wang
position: Ph.D. Candidate
affiliation: Department of Physics <br /> University of Illinois at Urbana-Champaign 
email: yuh.wang (at) outlook.com
keywords: minimal academic
google_scholar: https://scholar.google.com/
github_link: https://github.com/wangyh1949
linkedin: https://www.linkedin.com/in/yu-huan-wang-4a91161a5/
avatar: ./assets/img/Wang, Alvin_1196-2.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
